version: '3.8'

services:
  batchstrip:
    image: emmajhyde/batchstrip:latest
    container_name: batchstrip
    build:
      # build from current directory
      context: .
    # expose internal (docker) port 4000 to external (host) port 4000
    # allowing user to access at http://localhost:4000
    ports:
      - 4000:4000
