name: Build & Test Dev

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    env:
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
    steps:
      - uses: actions/checkout@v2

      - name: Test & Compile Development Build
        run: COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f ./docker/prod-compose.yml build

      - name: Run Development Build
        run: COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f ./docker/prod-compose.yml up -d

      - name: Tag Development Build
        run: docker tag batchstrip:latest emmajhyde/batchstrip:development

      - name: Authorize Deployment Procedure
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Deploy `docker.io/emmajhyde/batchstrip:development` Image to DockerHub
        run: docker push emmajhyde/batchstrip:development
