name: Build & Deploy

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test & Compile PR Build
        run: docker buildx bake -f ./docker/prod-compose.yml

      - name: Run PR Build
        run: docker-compose up -d -f ./docker/prod-compose.yml
