name: Build & Deploy

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test & Compile PR Build
        run: COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker/prod-compose.yml build

      - name: Run PR Build
        run: COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker/prod-compose.yml up -d
