name: Build, Test, Deploy Prod
on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    env:
      TAG_NAME: ${{ github.event.release.tag_name }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      PROD_BUILD_NAME: emmajhyde/batchstrip:${{ env.TAG_NAME }}
    steps:
      - uses: actions/checkout@v2

      - name: Run Testing Suite & Compile Production Build
        run: COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker/prod-compose.yml build --no-cache

      - name: Run Production Build
        run: COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker/prod-compose.yml up -d

      - name: Tag Production Build
        run: docker tag batchstrip:latest ${{ env.PROD_BUILD_NAME }}

      - name: Authorize Deployment Procedure
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Deploy `docker.io/emmajhyde/batchstrip` Image to DockerHub
        run: docker push ${{ env.PROD_BUILD_NAME }}
