name: Build, Test, Deploy Prod
on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    env:
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      
    steps:
      - uses: actions/checkout@v2

      - name: Run Testing Suite & Compile Production Build
        run: COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker/prod-compose.yml build --no-cache

      - name: Run Production Build
        run: COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker/prod-compose.yml up -d

      - name: Tag Production Build
        run: docker tag batchstrip:latest emmajhyde/batchstrip:${{ github.event.release.tag_name }}

      - name: Authorize Deployment Procedure
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Deploy `docker.io/emmajhyde/batchstrip` Production Image to DockerHub
        run: docker push emmajhyde/batchstrip:${{ github.event.release.tag_name }}
